version: '{build}'
branches:
  only:
  - main
skip_tags: true
image: Ubuntu2004
clone_folder: /home/appveyor/site

environment:
  HAXELIB_ROOT: /home/appveyor/haxelib
  HAXE_INSTALLDIR: /home/appveyor/haxe
  SRC_REPO: https://github.com/brandoge91/funkin-bcb
  GITHUB_ACCESS_TOKEN:
    secure: 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
install:
  - cd /home/appveyor/site
  - git checkout main
  - cd /home/appveyor
  - sudo add-apt-repository ppa:haxe/releases -y
  - sudo apt update
  - sudo apt install neko tar build-essential -y
  - wget https://github.com/HaxeFoundation/haxe/releases/download/4.1.5/haxe-4.1.5-linux64.tar.gz
  - mkdir $HAXE_INSTALLDIR
  - tar -xf haxe-4.1.5-linux64.tar.gz -C $HAXE_INSTALLDIR
  - export PATH=$PATH:$HAXE_INSTALLDIR/haxe_20201231082044_5e33a78aa
  - mkdir $HAXELIB_ROOT && haxelib setup $HAXELIB_ROOT
  - haxelib install lime 7.9.0
  - haxelib install openfl
  - haxelib install flixel
  - haxelib run lime setup flixel
  - haxelib run lime setup
  - haxelib install flixel-tools
  - haxelib install flixel-addons
  - haxelib install flixel-ui
  - haxelib install hscript
  - haxelib install markdown
  - haxelib install HtmlParser
  - haxelib install newgrounds
  - haxelib git polymod https://github.com/larsiusprime/polymod.git
  - haxelib git discord_rpc https://github.com/Aidan63/linc_discord-rpc
  - git clone $SRC_REPO /home/appveyor/src

build_script:
  - cd /home/appveyor/site
  - git config --global credential.helper store
  - ps: Set-Content -Path "$HOME\.git-credentials" -Value "https://$GITHUB_ACCESS_TOKEN:x-oauth-basic@github.com`n" -NoNewline  
  - git config --global user.email "brandoge91@gmail.com"
  - git config --global user.name "brandoge91"
  - cd /home/appveyor/src
  - haxelib run lime build html5
  - cd /home/appveyor/site
  - git rm -rf nightly/
  - cp -r /home/appveyor/src/export/release/html5/bin /home/appveyor/site/bin
  - mv /home/appveyor/site/bin /home/appveyor/site/nightly
  - git add --all
  - git commit -m "add nightly demo"
  - git push
deploy: off
